### ISSUE TITLE
Question : How to switch between tabs through fragments ?

### ISSUE THREAD

**Issue by pramodchoudhari** [rrispoli/SampleTabs#1]
Thanks for such clean and neat example of Tabs / Pager through MVVMCross. 👍 

I wish to switch between tabs, through a button inside each fragment. 
Currently we are moving to child view, but I want to switch to other tabs.

Could please help me on this ?

**Comment by rrispoli** [comment]
I didn't understand your doubt very well... But tell me if its helps you:

1) Create a custom MvxMessage on Core/Messages:
```
public class MainTabChangedMessage : MvxMessage
{
    public int CurrentPage { get; private set; }

    public MainTabChangedMessage(object sender, int currentPage) : base(sender)
    {
        CurrentPage = currentPage;
    }
}
```

2) On child button click command, publish a MainTabChangedMessage:
```
public ICommand ChangeTabCommand => new MvxCommand(DoChangeTabCommand);
private void DoChangeTabCommand()
{
    var currentPage = 10; //Your logic here
    Mvx.Resolve<IMvxMessenger>().Publish(new MainTabChangedMessage(this, currentPage));
}
```

3) On MainView (Android and iOS), subscribe the MainTabChangedMessage:
```
private readonly MvxSubscriptionToken _mainTabChangedSubscriptionToken;

//Inside OnCreateView (Android) and ViewDidLoad (iOS)
_mainTabChangedSubscriptionToken = Mvx.Resolve<IMvxMessenger>().Subscribe<MainTabChangedMessage>(OnMainTabChangedMessage);

//Android
private void OnMainTabChangedMessage(MainTabChangedMessage message)
{
    Activity.RunOnUiThread(() =>
    {
        viewPager.SetCurrentItem(ViewModel.CurrentPage, false);
    });
}

//iOS
private void OnMainTabChangedMessage(MainTabChangedMessage message)
{
    UIApplication.SharedApplication.InvokeOnMainThread(() =>
    {
        SelectedViewController = ViewControllers[message.CurrentPage];
        //SelectedIndex = message.CurrentPage;
    });
}
```

Other way is use a CurrentPage property on MainViewModel and use ViewModel.WeakSubscribe to check when the property changed.

And other way is use a CurrentPage property on MainViewModel and create custom bindings for SetCurrentItem (ViewPager) and SelectedViewController (iOS, though SelectedIndex works too, so maybe this already work). I never tried to test this way, but it can work.

**Comment by pramodchoudhari** [comment]
@rrispoli just to clear my question, so this will help other seeker.
I have three tabs each tab has button and 
Tab 1 button will navigate to Tab 2
Tab 2 button will navigate to Tab 3
And 
Tab 3 button will navigate to Tab 1


looks like your mvx message implementation will help. I will give it try.

**Comment by rrispoli** [comment]
Ok, now I understand what you want to do. 

Yes, the message approach will work, but I think you can move the buttons from fragments/childs to parent view (the same when you have the viewpager and tabbar).

I already do this in "introduction screens" for an app years ago, with just 2 bottom buttons:  PREVIOUS and NEXT. I control the visibility (PreviousButtonVisible and NextButtonVisibible) and text (PreviousButtonText and NextButtonText) of each button on the CurrentPage SET property and change the tabs publishing messages in the property SET too.

Well, you can combine all of this to implement what best work for you.

And don't let to try to test the custom bindings, it can save a lot of time for you. When I got some free time, I will test this. :)

**Comment by rrispoli** [comment]
Can I close this?

**Comment by pramodchoudhari** [comment]
Yes
